<a href="https://colab.research.google.com/github/ErlaVaishnavi/ALML_TNSIF_TRAINING/blob/main/Copy_of_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s=pd.Series([1,2,3,4,5,6,7,8])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
print(s.describe())

count    8.00000
mean     4.50000
std      2.44949
min      1.00000
25%      2.75000
50%      4.50000
75%      6.25000
max      8.00000
dtype: float64

In [ ]:
print(s.mean())
print(s.min())
print(s.max())
print(s.std())

4.5
1
8
2.449489742783178

Data Manipulation

In [ ]:
#map(function)
mapped=s.map(lambda x:x**2)
print(mapped)

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
dtype: int64

In [ ]:
#apply(function)
applied=s.apply(lambda x:x*2)
print(applied)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
dtype: int64

In [ ]:
#sort_values()
sorted=s.sort_values()
print(sorted)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
s1=pd.Series([1,5,6,4,9,22,13,11])
print(s1)
sorted=s1.sort_values()
print(sorted)

0     1
1     5
2     6
3     4
4     9
5    22
6    13
7    11
dtype: int64
0     1
3     4
1     5
2     6
4     9
7    11
6    13
5    22
dtype: int64

In [ ]:
s1.drop(5)

0     1
1     5
2     6
3     4
4     9
6    13
7    11
dtype: int64

Handling Missing Data

In [ ]:
#isnull()
s2=pd.Series([1,12,14,np.nan,1.1,16,76])
print(s2)
s2.isnull()

0     1.0
1    12.0
2    14.0
3     NaN
4     1.1
5    16.0
6    76.0
dtype: float64

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [ ]:
#notnull()
s2.notnull()

0     True
1     True
2     True
3    False
4     True
5     True
6     True
dtype: bool

In [ ]:
#fillna
s2.fillna(0)

0     1.0
1    12.0
2    14.0
3     0.0
4     1.1
5    16.0
6    76.0
dtype: float64

In [ ]:
#dropna()
s2.dropna()

0     1.0
1    12.0
2    14.0
4     1.1
5    16.0
6    76.0
dtype: float64

Indexing,Slicing and Filtering

In [ ]:
#iloc()
print(s.iloc[3])
print(s1.iloc[-4])
print(s2.iloc[5 & -2])

4
9
1.1

In [ ]:
#loc()
print(s2.loc[5])

16.0

In [ ]:
#(s>n)

Aggregation

In [ ]:
#Sum()
print(s.sum())
print(s1.sum())
print(s2.sum())

36
71
120.1

In [ ]:
#cumsum()
print(s.cumsum())
print(s1.cumsum())
print(s2.cumsum())

0     1
1     3
2     6
3    10
4    15
5    21
6    28
7    36
dtype: int64
0     1
1     6
2    12
3    16
4    25
5    47
6    60
7    71
dtype: int64
0      1.0
1     13.0
2     27.0
3      NaN
4     28.1
5     44.1
6    120.1
dtype: float64

In [ ]:
#aggregate()
print(s.aggregate(['mean','std','sum','min','max']))
print(s1.aggregate(['mean','std','sum','min','max']))
print(s2.aggregate(['mean','std','sum','min','max']))

mean     4.50000
std      2.44949
sum     36.00000
min      1.00000
max      8.00000
dtype: float64
mean     8.875000
std      6.577831
sum     71.000000
min      1.000000
max     22.000000
dtype: float64
mean     20.016667
std      28.178745
sum     120.100000
min       1.000000
max      76.000000
dtype: float64