<a href="https://colab.research.google.com/github/ErlaVaishnavi/ALML_TNSIF_TRAINING/blob/main/Presentation_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing Libraries

import numpy as np
import pandas as pd
import plotly.express as px

In [3]:
#loading dataset
df= pd.read_excel("/content/Presentation-TASK (1).xlsx")

In [4]:

df.describe()

       Communication    Attrire  Marks
count      57.000000  55.000000    0.0
mean        6.105263   3.763636    NaN
std         1.029636   0.543093    NaN
min         3.000000   3.000000    NaN
25%         6.000000   3.000000    NaN
50%         6.000000   4.000000    NaN
75%         7.000000   4.000000    NaN
max        10.000000   5.000000    NaN

In [7]:
df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UID                  71 non-null     object
 1   Participant Name     77 non-null     object
 2   Unnamed: 2           62 non-null     object
 3   Project Name         36 non-null     object
 4   Technical knowledge  61 non-null     object
 5   Communication        57 non-null     float64
 6   Attrire              55 non-null     float64
 7   Marks                0 non-null      float64
dtypes: float64(3), object(5)
memory usage: 5.4+ KB

In [30]:
# Check missing values
print(df.isnull().sum())

# Add a check to re-load df if it's empty, ensuring continuity
# This addresses cases where df might become empty due to environment resets or unintended executions.
if df.empty:
    print("DataFrame is empty, re-loading data to ensure processing continues.")
    df = pd.read_excel("/content/Presentation-TASK (1).xlsx")

# Convert 'Technical knowledge' to numeric and fill NaNs with 0, ensuring float type
df['Technical knowledge'] = pd.to_numeric(df['Technical knowledge'], errors='coerce').fillna(0).astype(float)

# Fill NaN values in 'Communication' and 'Attrire' with 0 and ensure float type
df['Communication'] = df['Communication'].fillna(0).astype(float)
df['Attrire'] = df['Attrire'].fillna(0).astype(float)

# IMPORTANT: Removed df.dropna() as it was making the DataFrame empty.
# If you need to drop rows with NaNs in other specific columns, use df.dropna(subset=['column_name']) for targeted removal.

# Check for duplicate records (Do NOT remove duplicates)
print("Duplicate Records:", df.duplicated().sum())

# Create Total Marks column
# All components are now numeric (float), so 'Total Marks' will be numeric (float).
df["Total Marks"] = df["Technical knowledge"] + df["Communication"] + df["Attrire"]

# Verify the updated dataset
print(df.head())

UID                    14
Participant Name        8
Unnamed: 2             23
Project Name           49
Technical knowledge     0
Communication           0
Attrire                 0
Marks                  85
Total Marks             0
dtype: int64
Duplicate Records: 7
          UID       Participant Name Unnamed: 2  \
0         NaN                    NaN   Group No
1  T160600201        Gayathri Munasu          3
2  T160600202       Namratha Bajjuri          4
3  T160600203       Nikitha Sambangi        NaN
4  T160600204  Akhil Reddy Komireddy          3

                         Project Name  Technical knowledge  Communication  \
0                                 NaN                 10.0           10.0
1  types of Data visuals,application                   6.0            6.0
2                Comparision of t-SNE                  6.0            6.0
3                                 NaN                  0.0            0.0
4                                 KNN                  6.0            7.0

   Attrire  Marks  Total Marks
0      5.0    NaN         25.0
1      3.0    NaN         15.0
2      4.0    NaN         16.0
3      0.0    NaN          0.0
4      3.0    NaN         16.0

In [33]:
# Top 5 by Total Marks
top_total = df.nlargest(5, "Total Marks")
print("\nTop 5 by Total Marks")
print(top_total[['Participate Name','Total Marks']])

# Top 5 in Technical knowledge
top_technical = df.nlargest(5, "Technical knowledge")
print("\nTop 5 in Technical")
display(top_technical[['Participant Name','Technical knowledge']])

# Top 5 in Communication
top_communication = df.nlargest(5, "Communication")
print("\nTop 5 in Communication")
print(top_communication[['Participate Name','Communication']])

# Top 5 in Attrire
top_attrire = df.nlargest(5, "Attrire")
print("\nTop 5 in Attrire")
print(top_attrire[['Participate Name','Attrire']])

Top 5 by Total Marks
       Participant Name  Total Marks
0                   NaN         25.0
7      BOPPANI BHARGAVI         19.0
65      Gajula Sathvika         19.0
22  Madipadiga Kousheel         18.0
23      Kanigiri Devika         18.0

Top 5 in Technical

                     Participant Name  Technical knowledge
0                                 NaN                 10.0
7                    BOPPANI BHARGAVI                  8.0
45  SRI SAI MADHURVIND MUDUTHANAPELLY                  8.0
65                    Gajula Sathvika                  8.0
8                AjithReddy Anumandla                  7.0

Top 5 in Communication
                Participant Name  Communication
0                            NaN           10.0
4          Akhil Reddy Komireddy            7.0
5                   CHARAN KONDA            7.0
7               BOPPANI BHARGAVI            7.0
18  PEETHALA JYOTHI SWAROOP BABU            7.0

Top 5 in Attrire
        Participant Name  Attrire
0                    NaN      5.0
29  Mohammed Masoom Baba      5.0
36        Vaishnavi Erla      5.0
2       Namratha Bajjuri      4.0
6              Md Faisal      4.0

In [34]:
# Visualization for top 5 students
top_total = df.nlargest(5, "Total Marks")

fig = px.bar(
    top_total,
    x="Participant Name",
    y="Total Marks",
    color="Total Marks",
    text="Total Marks",
    title="Top 5 Students by Total Marks"
)

fig.update_traces(textposition="outside")
fig.show()

In [39]:
#Visualization for top 5 students in Technical knowlegde
top_technical = df.nlargest(5, "Technical knowledge")

fig = px.bar(
    top_technical,
    x="Participant Name",
    y="Technical knowledge",
    color="Technical knowledge",
    text="Technical knowledge",
    title="Top 5 Students in Technical knowledge"
)

fig.update_traces(textposition="outside")
fig.show()

In [40]:
#Visualization for top 5 students in Communication
top_communication = df.nlargest(5, "Communication")

fig = px.bar(
    top_communication,
    x="Participant Name",
    y="Communication",
    color="Communication",
    text="Communication",
    title="Top 5 Students in Communication"
)

fig.update_traces(textposition="outside")
fig.show()

In [41]:
#Visualization for top 5 students in attrire
top_attire = df.nlargest(5, "Attrire")

fig = px.bar(
    top_attrire,
    x="Participant Name",
    y="Attrire",
    color="Attrire",
    text="Attrire",
    title="Top 5 Students in Attrire"
)

fig.update_traces(textposition="outside")
fig.show()